# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions

# Name of the workflow
name: Check

# When to run
on:
  push:
    branches-ignore:
      - gh-pages
  pull_request:
    branches-ignore:
      - gh-pages

# Run R-CMD-check in multiple platforms
jobs:
  Check:
    runs-on: ${{ matrix.os }}

    name: ${{ matrix.os }} (${{ matrix.r }})

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-16.04]
        r: ['oldrel', 'release']
        include:
          - os: ubuntu-16.04
            r: 'devel'

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      _R_CHECK_CRAN_INCOMING_REMOTE_: false
      CHESS_TEST: 1

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.r }}

      - uses: r-lib/actions/setup-pandoc@v1

      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ matrix.r }}-lib-${{ github.sha }}
          restore-keys: ${{ runner.os }}-r-${{ matrix.r }}-lib-

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get install librsvg2-dev libcurl4-openssl-dev libssl-dev libicu-dev

      - name: Install R dependencies
        run: |
          install.packages(c('remotes', 'rcmdcheck'))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Install Miniconda
        run: |
          install.packages('reticulate')
          reticulate::install_miniconda()
        shell: Rscript {0}

      - name: Configure Miniconda on MacOS
        if: runner.os == 'macOS'
        run: echo "options(reticulate.conda_binary = reticulate:::miniconda_conda())" >> .Rprofile

      - name: Install python-chess
        run: |
          remotes::install_local()
          chess::install_chess()
        shell: Rscript {0}

      - name: Check package
        run: rcmdcheck::rcmdcheck(args = c("--no-manual", "--as-cran"), error_on = "warning", check_dir = "check")
        shell: Rscript {0}

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@main
        with:
          name: ${{ runner.os }}-r${{ matrix.r }}-results
          path: check
