on:
  push:
    branches:
      - main
      - master

name: Pages

jobs:
  Pages:
    runs-on: ubuntu-16.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      CHESS_TEST: 1
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1

      - uses: r-lib/actions/setup-pandoc@v1

      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ matrix.r }}-lib-${{ github.sha }}
          restore-keys: ${{ runner.os }}-r-${{ matrix.r }}-lib-

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get install librsvg2-dev libcurl4-openssl-dev libssl-dev libicu-dev

      - name: Install R dependencies
        run: |
          install.packages(c('remotes', 'rcmdcheck', 'pkgdown'))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Install Miniconda
        run: |
          install.packages('reticulate')
          reticulate::install_miniconda()
        shell: Rscript {0}

      - name: Install python-chess
        run: |
          remotes::install_local()
          chess::install_chess()
        shell: Rscript {0}

      - name: Install package
        run: R CMD INSTALL .

      - name: Deploy package
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE)'
